name: gatt
description: GATT (Generic ATTribute profile) structured data for BLE communication.
version: 1.0.0

environment:
  sdk: '>=2.15.0-268.8.beta <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
